#TD2 v2

FROM alpine:3.15 as builder
WORKDIR /app
RUN apk add --no-cache nodejs npm 
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM alpine:3.15 as runner
WORKDIR /app
RUN apk add --no-cache nodejs
RUN adduser -D node
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/dist ./dist
USER node
CMD ["node", "dist/index.js"]